apiVersion: apps/v1
kind: Deploymet
metadata:
   name: my_app
spec:
  replicas: 3
  selecetor:
    matchLabels: 
      app: my-app
  strategytype: RollingUpdate 
  template:
    metadata:
      Labels:
        app : 
    spec: 
      containers:
      - name: nginx
        image: nginx
        port: 80
        - containerPort: 8080
